### PR TITLE
feat(TextLink): improve inverse variant

### PR DESCRIPTION
**Pull request by yceballost**
https://github.com/Telefonica/mistica-design/issues/640

### CODE REVIEW

**Review by aweell — APPROVED** [review]
👏👏👏

**Comment by pladaria** [comment]
some more screenshot tests could be added:

- inverse
- darkMode
- darkMode + inverse (if that makes sense)

**Review by pladaria — APPROVED** [review]

**Comment by yceballost** [comment]
> some more screenshot tests could be added:
> 
> * inverse
> * darkMode
> * darkMode + inverse (if that makes sense)

By the moment, darkMode + inverse isn't useful.

**Pull request merged**
