### PR TITLE
feat(Chip): change background color on hover/active

### PR DESCRIPTION
**Pull request by tuentisre**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

https://jira.tid.es/browse/WEB-2110

### CODE REVIEW

**Review by pladaria — APPROVED** [review]

**Comment by aweell** [comment]
When is not active and is being hovered, text of the chip shouldn't change to `textActivated` but remain in `textPrimary`.

https://mistica-jopq1isi0-flows-projects-65bb050e.vercel.app/?path=/story/components-chip--single-selection

In the example in Movistar we can see the text of inactive chips to change to blue when hovered.

**Review by aweell — APPROVED** [review]

**Comment by andredelramo-hm** [comment]
It would be necessary to include the pressed state

**Comment by atabel** [comment]
> It would be necessary to include the pressed state

hmmm... what do you mean. It should already have pressed state. For example: https://mistica-qgteupypi-flows-projects-65bb050e.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8AFATjAbgSxgdwBUIIAbAZwAIB6APgB0A7JAYQAtsAHCiB9GMsgF5gACgCUFQTQrAAvrJptOSKko70GIADQgALqxgBbOIgBCJAIYBXELKA

**Comment by andredelramo-hm** [comment]
You're right, when the chip only has the onPress property, it does appear, but in a[ multi-selection](https://mistica-qgteupypi-flows-projects-65bb050e.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA6A7VAeASgQygSwgHEAnCAVwAcACFbAWxgF4lwALPCgWgHNTKWqsAGbYyAGwAuANWxiyTFgEYWAPlRUq6AJIoxeFDCoBnCtjBNgADgC%2BalBo1ZcBAEJkJEiGnsONAN1l5ZhBlZB9fYhgUWGJGYAAKYCowVhgwAGsYKAAaKjFsACMYMS0oKmsASipGFSp49V8HdABhdmozCTw-CxS0zKhrKjwoOPyikoGqLUgUOOmvABk8blYJFH1uADE8MTEs2wbGh1aOKmVwxvQAehOKOyOK60OqK-umnHwINw8vZ-9AhQgABMLD%2BVEi0RgsQSSV6GSyuTGxVK5SqNTqYMctyoHS6PVS8Mmw1GhWRk3ms2AFKWKzWG22u32byOGmxIIuvmut2ZDkez1ezycn2%2Bnm8RwCckBAGZQRzwVEYnFEskCf1EaSJqjqrV6nKsW0cWBOt04nD%2BoNicAkRNBhS5jMaat1igtjs9gMeUdsTK9Zobm1PVQ%2BRcBT5rjo9AY7NcPgQSOQ7qgQNYgA), it doesn't show.

**Comment by atabel** [comment]
> You're right, when the chip only has the onPress property, it does appear, but in a[ multi-selection](https://mistica-qgteupypi-flows-projects-65bb050e.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA6A7VAeASgQygSwgHEAnCAVwAcACFbAWxgF4lwALPCgWgHNTKWqsAGbYyAGwAuANWxiyTFgEYWAPlRUq6AJIoxeFDCoBnCtjBNgADgC%2BalBo1ZcBAEJkJEiGnsONAN1l5ZhBlZB9fYhgUWGJGYAAKYCowVhgwAGsYKAAaKjFsACMYMS0oKmsASipGFSp49V8HdABhdmozCTw-CxS0zKhrKjwoOPyikoGqLUgUOOmvABk8blYJFH1uADE8MTEs2wbGh1aOKmVwxvQAehOKOyOK60OqK-umnHwINw8vZ-9AhQgABMLD%2BVEi0RgsQSSV6GSyuTGxVK5SqNTqYMctyoHS6PVS8Mmw1GhWRk3ms2AFKWKzWG22u32byOGmxIIuvmut2ZDkez1ezycn2%2Bnm8RwCckBAGZQRzwVEYnFEskCf1EaSJqjqrV6nKsW0cWBOt04nD%2BoNicAkRNBhS5jMaat1igtjs9gMeUdsTK9Zobm1PVQ%2BRcBT5rjo9AY7NcPgQSOQ7qgQNYgA), it doesn't show.

ok, it should be fixed now. I thought the pressed state was only intended to be applied to button/link chips. With the latest changes, it should apply to any interactive chip, including checkbox/radio (single/multi selection) chips

**Comment by andredelramo-hm** [comment]
Great! It looks good now, just one small detail, the overlay doesn't reach the right edge of the chip.
Captura de pantalla 2024-12-19 a las 13 28 45
Could it be for the border?

**Review by andredelramo-hm — APPROVED** [review]
Now it's perfect :)

**Review by atabel — APPROVED** [review]

**Review by aweell — APPROVED** [review]

**Pull request merged**
