### PR TITLE
feat(Accordion, BoxedAccordion): allow detail and right content in header

### PR DESCRIPTION
**Pull request by marcoskolodny**
Issue: [Link](https://jira.tid.es/browse/WEB-2091)

### CODE REVIEW

**Review by pladaria — APPROVED** [review]

**Comment by aweell** [comment]
How i can change the default label the accordion button has when using an screen reader?

Screenshot 2024-11-08 at 19 06 50

**Comment by marcoskolodny** [comment]
> How can I change the default label the accordion button has when using an screen reader?
> 

@aweell Oops, good catch! Should be fixed now :)

**Review by yceballost — APPROVED** [review]

**Review by yceballost — COMMENTED** [review]
missing inverse screenshot for accordions with detail (no boxed)

**Comment by marcoskolodny** [comment]
> missing over inverse screenshot for accordions with detail (no boxed)

@yceballost added :)

**Review by atabel — APPROVED** [review]

**Pull request merged**
