### PR TITLE
fix(AdvancedDataCard): touchable area didn't cover the whole card in some cases

### PR DESCRIPTION
**Pull request by BrunoGuimaraes103**
Fixed touchable size bugs when the extra doesn't cover the minimum height size and halving the size of the slots.

Bug 1 : 
image

Bug 2 : 
image

### CODE REVIEW

**Comment by BrunoGuimaraes103** [comment]
@vinrosa

**Comment by vinrosa** [comment]
the scenario case that trigger the fix its now work perfect

**Review by yceballost — APPROVED** [review]

**Review by atabel — COMMENTED** [review]
please can you provide a playroom with a reproduction of the issue and a playroom with the fix (using this PR playroom deploy)?

**Comment by vinrosa** [comment]
> 

[Playroom](https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A%2BAHWM0yQEEoA3XYsGFAAiuAC64AwrgBOUFmzajCogDYxyTEIDJATFIDOuXRGIww4qLk3yFS1TA56NIABYAmK6wUx0o6bkoA2tYK7ADKhAC22GooKhBgANbBIZiRuKTqwEgAkpDEAOoyxCSkAEowpACuKjKYkHHSlPUQ0noAdABGfsRQdJgA9Ax0ySGwemDShNhKxk4cKqQQmLCVmDDSflBL2C2YuACOlYQANJjc8QBXONAwmKIwxOLSmBG4hHp3MrAeKQMMx8kALrDTxsYwSOJ6TIACgAlJhyAxMAB3EhbZFtXBqaSiaGaMCQmCaWEgkLGAAK0hgekcwDhCKRqJ6EAxWPWuPxKkIiWJpL%2BLCQ-TQ6GYxFQGBw%2BCIZEotEY1k4PD4AmEYkkX2StjUTh0%2BkMEmMpnMlhAmuUagcTjcPy8Pj8gRGYXEiRKAHFpBBKthHWxXuhsvcIrSAKx834RFowAMwIOhUQAT21wGAd3j2Bg8Ew%2BMI0gJRJApz0hAAXhnMDQACyYOhhhSi35sTi8J6YIulyiVvp6XNW0SibB6eD9fp6T25mBtSrEPTRXB6ZxtSARfo0AAMq-Qa9X-QA-AAzXACTT80EpJtq55tzKd1s9zTOPsDocjscCSfT2fzxcQZdbzfr3cDyPEATwbdgOGbWorw7CsuzvFxH0HYdR0qcd3xnGovyXFd13-bd90PfNQIbc8W2g4Ab27MBe37JCX1Qt8pwwucF2wv8t0Awjj0GH1wMgy8S2vWDb2o%2B9EOfFC0KYz9WJ-HCNw4gjgOI35SKgwSYLg0SENoiTXwnaTMNk39cMUoCiJ409G36ONDwSN0PS9f4gVrcFCUoelERRNEWUxbEOXAQleWSCkqRpDz4S8pl0T89k8UC7kkhAElrEswVhVFAsQFEZwY2pBAAhAAA1QhzgAfQAORgZEQEBY4QFRKAcr0AqAGY12BIA) with the issue

[Playroom](https://mistica-degshgqe5-tuentisre.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A%2BAHWM0yQEEoA3XYsGFAAiuAC64AwrgBOUFmzajCogDYxyTEIDJATFIDOuXRGIww4qLk3yFS1TA56NIABYAmK6wUx0o6bkoA2tYK7ADKhAC22GooKhBgANbBIZiRuKTqwEgAkpDEAOoyxCSkAEowpACuKjKYkHHSlPUQ0noAdABGfsRQdJgA9Ax0ySGwemDShNhKxk4cKqQQmLCVmDDSflBL2C2YuACOlYQANJjc8QBXONAwmKIwxOLSmBG4hHp3MrAeKQMMx8kALrDTxsYwSOJ6TIACgAlJhyAxMAB3EhbZFtXBqaSiaGaMCQmCaWEgkLGAAK0hgekcwDhCKRqJ6EAxWPWuPxKkIiWJpL%2BLCQ-TQ6GYxFQGBw%2BCIZEotEY1k4PD4AmEYkkX2StjUTh0%2BkMEmMpnMlhAmuUagcTjcPy8Pj8gRGYXEiRKAHFpBBKthHWxXuhsvcIrSAKx834RFowAMwIOhUQAT21wGAd3j2Bg8Ew%2BMI0gJRJApz0hAAXhnMDQACyYOhhhSi35sTi8J6YIulyiVvp6XNW0SibB6eD9fp6T25mBtSrEPTRXB6ZxtSARfo0AAMq-Qa9X-QA-AAzXACTT80EpJtq55tzKd1s9zTOPsDocjscCSfT2fzxcQZdbzfr3cDyPEATwbdgOGbWorw7CsuzvFxH0HYdR0qcd3xnGovyXFd13-bd90PfNQIbc8W2g4Ab27MBe37JCX1Qt8pwwucF2wv8t0Awjj0GH1wMgy8S2vWDb2o%2B9EOfFC0KYz9WJ-HCNw4gjgOI35SKgwSYLg0SENoiTXwnaTMNk39cMUoCiJ409G36ONDwSN0PS9f4gVrcFCUoelERRNEWUxbEOXAQleWSCkqRpDz4S8pl0T89k8UC7kkhAElrEswVhVFAsQFEZwY2pBAAhAAA1QhzgAfQAORgZEQEBY4QFRKAcr0AqAGY12BIA) after the fix

**Review by atabel — APPROVED** [review]

**Pull request merged**
